name: pegasus_pdv
description: T2Ti ERP - Pegasus PDV

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

# version:A.B.C+X --> A.B.C represents the versionName such as 1.0.0 - X (the number after the +) represents the versionCode such as 1, 2, 3, etc.
version: 1.0.8+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^5.0.0 #^3.1.0
  intl:
  font_awesome_flutter:
  backdrop: ^0.6.0
  http: ^0.13.0 #^0.12.2
  flutter_masked_text: ^0.8.0
  cpf_cnpj_validator: ^1.0.5
  flutter_html: ^2.1.2
  bottomreveal: ^1.0.0
  flutter_barcode_scanner: ^2.0.0-nullsafety.0 #^1.0.2
  flutter_bootstrap: ^1.0.1
  flutter_sparkline: ^0.1.0
  printing: ^5.1.0
  moor: #^3.4.0 #^4.1.0
  sqlite3_flutter_libs: #^0.4.1 
  path_provider: #^2.0.1 
  path: #^1.8.0
  awesome_dialog: ^1.3.2
  image_picker: ^0.7.3
  catcher: ^0.6.3
  sentry_flutter: ^4.0.6
  desktop_window: ^0.4.0
  url_launcher: ^6.0.2
  email_validator: ^1.0.6
  flutter_dotenv: ^3.1.0
  encrypt: ^5.0.0
  bottom_navy_bar: ^6.0.0
  flutter_spinbox: ^0.5.2
  ini: ^2.1.0
  custom_radio_grouped_button: any
  csv: ^5.0.0
  file_picker: ^4.0.0
  crypto: ^3.0.1
  share_plus: ^2.1.4

  # get_it: ^1.0.3+2
  # recase: ^3.0.0
  # xml: ^3.6.1
  # fluttertoast: ^4.0.0
  # flutter_plugin_pdf_viewer: ^1.0.7
  # pdf_viewer_plugin: ^1.0.0+2
  # cached_network_image: 
  # flutter_swiper: ^1.1.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2 #^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: # use the latest version
  build_runner:
  msix: ^1.0.6
  flutter_launcher_icons: ^0.9.0
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher_icon.png"  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/fonts/
     - assets/text/
     - .env
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

msix_config:
  display_name: T2Ti Pegasus PDV
  publisher_display_name: T2Ti.COM
  identity_name: T2Ti.COM.T2TiPegasusPDV
  msix_version: 1.0.8.0
  publisher: CN=0A6E4754-6ACC-44ED-81F6-94B57BF2E8BC
  logo_path: C:\T2Ti ERP\ERP 3.0 Programas e Fontes\Flutter\pegasus_pdv\assets\images\logo_pegasus_pdv.png
  capabilities: internetClient,systemManagement,pointOfService,bluetooth
  store: true